export const FETCH_ALL_PERSONAL_TASK = "FETCH_ALL_PERSONAL_TASK";
export const INSERT_PERSONAL_TASK = "INSERT_PERSONAL_TASK";
export const MARK_AS_COMPLETED = "MARK_AS_COMPLETED";
export const EDIT_PERSONAL_TASK = "EDIT_PERSONAL_TASK";
export const DELETE_PERSONAL_TASK = "DELETE_PERSONAL_TASK";
// Projects
export const CREATE_PROJECT = "CREATE_PROJECT";
export const ALL_PROJECTS = "ALL_PROJECTS";